[project]
name = "wtq-rembg-comfyui-node"
description = "This custom node is based on the [a/rembg-comfyui-node](https://github.com/Jcd1230/rembg-comfyui-node) but provides additional functionality to select ONNX models."
version = "1.0.0"
license = "LICENSE"

[project.urls]
Repository = "https://github.com/waytooquick/wtq-rembg-comfyui-node"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "wtq"
DisplayName = "wtq-rembg-comfyui-node"
Icon = ""
